version: '3.7'
services:

  elastic:
    image: elasticsearch-fcs
    build:
      context: ./docker-images/elasticsearch-fcs-plugin/
    environment:
    - node.name=elastic
    - bootstrap.memory_lock=true
    - cluster.initial_master_nodes=elastic
    - network.host=_site_
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
    - ./docker-data/esdata:/usr/share/elasticsearch/data:delegated
    - ./docker-data/esdata/snapshots:/usr/share/elasticsearch/data/snapshots
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.0
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_HOSTS: http://elastic:9200/
    ports:
      - "5601:5601"
    depends_on:
      - elastic
