version: '3.7'
services:

  elastic:
    image: elasticsearch-nn
    build:
      context: ./docker-images/elasticsearch-nn-plugin/
    environment:
    - node.name=elastic
    - bootstrap.memory_lock=true
    - cluster.initial_master_nodes=elastic
    - network.host=_site_
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
    - ./data/esdata1:/usr/share/elasticsearch/data:delegated
    - ./data/esdata/snapshots:/usr/share/elasticsearch/data/snapshots
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/elasticsearch/kibana:7.3.0
    ports:
      - "5601:5601"
    depends_on:
      - elastic
