version: '3.7'
services:

  elastic:
    image: elasticsearch-nn
    build:
      context: ./docker-images/elasticsearch-nn-plugin/
    environment:
    - node.name=elastic
    - bootstrap.memory_lock=true
    - cluster.initial_master_nodes=elastic
    - network.host=_site_
    - path.repo=/usr/share/elasticsearch/data/snapshots
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
    - ./data/esdata1:/usr/share/elasticsearch/data:delegated
    - ./data/esdata/snapshots:/usr/share/elasticsearch/data/snapshots
    - ./config/elastic/:/usr/share/elasticsearch/external
    networks:
    - gs2-net

  kibana:
    image: docker.elastic.co/elasticsearch/kibana:7.3.0
    volumes:
    - ./config/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - gs2-net
    depends_on:
      - elastic
